name: vuelink_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy: ^6.0.2
  permission_handler: ^11.3.1
  device_info_plus: ^11.4.0
  logging: ^1.2.0
  crypto: ^3.0.3
  battery_plus: ^5.0.3
  ble_peripheral: ^2.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  # uni_links: ^0.5.1 # Replaced by app_links
  app_links: ^6.4.0 # Use suggested version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
